on:
  pull_request:
    branches:
      - testing
    types: [closed]
env:
  PR_NAME: ${{ github.event.pull_request.number }}
jobs:
  delete-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Github author authentication
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
      - name: Delete pr branch
        run: git push origin --delete storybook-pre-${{env.PR_NAME}}
