on:
  push:
    branches:
      - testing
  pull_request:
    branches:
      - testing
env:
  BRANCH_NAME: storybook-preview-${{ github.event.pull_request.number }}
  HOST: ${{ secrets.PREVIEW_HOST }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Github author authentication
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
      - name: install dependencies
        run: yarn install
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
      - name: build storybook
        run: yarn build-storybook
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
      - name: deploy storybook if testing
        if: ${{ github.ref == 'refs/heads/testing' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./storybook-static
      - name: deploy storybook on pr
        if: ${{ github.ref != 'refs/heads/testing' }}
        run: |
          git fetch --unshallow origin
          git checkout -b ${{env.BRANCH_NAME}}
          git rm -r --ignore-unmatch *
          mv -v ./storybook-static/* .
          git add .
          git commit -m ${{env.BRANCH_NAME}}
          git push -f origin ${{env.BRANCH_NAME}}
      - name: Comment pr
        if: ${{ github.ref != 'refs/heads/testing' }}
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: 'Preview deploy https://${{env.BRANCH_NAME}}.${{env.HOST}}'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

