on:
  push:
    branches:
      - main
      - testing
  pull_request:
    branches:
      - main
      - testing
env:
  PR_NAME: ${{ github.event.pull_request.node_id }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: install dependencies
        run: yarn install
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
      - name: build storybook
        run: yarn build-storybook
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
      - name: deploy storybook if main
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./storybook-static
      - name: deploy storybook if testing
        if: ${{ github.ref == 'refs/heads/testing' }}
        uses: nwtgck/actions-netlify@v1.2
        with:
          publish_dir: ./storybook-static
          NETLIFY_AUTH_TOKEN: ${{secrets.NETLIFY_TOKEN}}
          NETLIFY_SITE_ID: ${{secrets.NETLIFY_SITE_ID}}

